### ISSUE TITLE
scheduler_1  | KeyError: 'op'

### ISSUE THREAD

**Issue by arpit1997** [dask/dask-docker#24]
Platform: `ubuntu 16.04, Docker version 18.03.0-ce, docker-compose version 1.21.0`

Exception when `docker-compose up`

```
scheduler_1  | Future exception was never retrieved
scheduler_1  | future: <Future finished exception=KeyError('op',)>
scheduler_1  | Traceback (most recent call last):
scheduler_1  |   File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1113, in run
scheduler_1  |     yielded = self.gen.send(value)
scheduler_1  |   File "/opt/conda/lib/python3.6/site-packages/distributed/core.py", line 276, in handle_comm
scheduler_1  |     op = msg.pop('op')
scheduler_1  | KeyError: 'op'
scheduler_1  | Future exception was never retrieved
scheduler_1  | future: <Future finished exception=KeyError('op',)>
scheduler_1  | Traceback (most recent call last):
scheduler_1  |   File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1113, in run
scheduler_1  |     yielded = self.gen.send(value)
scheduler_1  |   File "/opt/conda/lib/python3.6/site-packages/distributed/core.py", line 276, in handle_comm
scheduler_1  |     op = msg.pop('op')
scheduler_1  | KeyError: 'op'
scheduler_1  | Future exception was never retrieved
scheduler_1  | future: <Future finished exception=KeyError('op',)>
scheduler_1  | Traceback (most recent call last):
scheduler_1  |   File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1113, in run
scheduler_1  |     yielded = self.gen.send(value)
scheduler_1  |   File "/opt/conda/lib/python3.6/site-packages/distributed/core.py", line 276, in handle_comm
scheduler_1  |     op = msg.pop('op')
scheduler_1  | KeyError: 'op'
```

**Comment by mollyporph** [comment]
Getting the same error. Did you solve it @arpit1997 ?

**Comment by mrocklin** [comment]
This is usually due to a version mismatch.  I suspect that you are connecting with a client that has a different version than is on the docker image.

**Comment by jacobtomlinson** [comment]
Closing due to inactivity.
