### ISSUE TITLE
Failed to start notebook

### ISSUE THREAD

**Issue by xiongmozhou** [dask/dask-docker#246]
dask-docker-notebook-1   | Fail to get yarn configuration. /opt/conda/bin/node[14]: ../../src/node_platform.cc:61:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
dask-docker-notebook-1   |  1: 0x7f9892706c39 node::Abort() [/opt/conda/bin/../lib/libnode.so.102]
dask-docker-notebook-1   |  2: 0x7f9892706ccb  [/opt/conda/bin/../lib/libnode.so.102]
dask-docker-notebook-1   |  3: 0x7f989278526d node::WorkerThreadsTaskRunner::WorkerThreadsTaskRunner(int) [/opt/conda/bin/../lib/libnode.so.102]
dask-docker-notebook-1   |  4: 0x7f9892785352 node::NodePlatform::NodePlatform(int, v8::TracingController*, v8::PageAllocator*) [/opt/conda/bin/../lib/libnode.so.102]
dask-docker-notebook-1   |  5: 0x7f98926c8ed7  [/opt/conda/bin/../lib/libnode.so.102]
dask-docker-notebook-1   |  6: 0x7f98926c9432 node::InitializeOncePerProcess(int, char**, node::InitializationSettingsFlags, node::ProcessFlags::Flags) [/opt/conda/bin/../lib/libnode.so.102]
dask-docker-notebook-1   |  7: 0x7f98926c957a node::InitializeOncePerProcess(int, char**) [/opt/conda/bin/../lib/libnode.so.102]
dask-docker-notebook-1   |  8: 0x7f98926c95d7 node::Start(int, char**) [/opt/conda/bin/../lib/libnode.so.102]
dask-docker-notebook-1   |  9: 0x7f9891d05d90  [/lib/x86_64-linux-gnu/libc.so.6]
dask-docker-notebook-1   | 10: 0x7f9891d05e40 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
dask-docker-notebook-1   | 11: 0x560d59cb9145  [/opt/conda/bin/node]
dask-docker-notebook-1   | 
dask-docker-scheduler-1  | 2022-09-01 12:13:41,710 - distributed.scheduler - INFO - -----------------------------------------------
dask-docker-notebook-1   | OpenBLAS blas_thread_init: pthread_create failed for thread 1 of 8: Operation not permitted
dask-docker-notebook-1   | OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
dask-docker-notebook-1   | OpenBLAS blas_thread_init: pthread_create failed for thread 2 of 8: Operation not permitted
dask-docker-notebook-1   | OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
dask-docker-notebook-1   | OpenBLAS blas_thread_init: pthread_create failed for thread 3 of 8: Operation not permitted
dask-docker-notebook-1   | OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
dask-docker-notebook-1   | OpenBLAS blas_thread_init: pthread_create failed for thread 4 of 8: Operation not permitted
dask-docker-notebook-1   | OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
dask-docker-notebook-1   | OpenBLAS blas_thread_init: pthread_create failed for thread 5 of 8: Operation not permitted
dask-docker-notebook-1   | OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
dask-docker-notebook-1   | OpenBLAS blas_thread_init: pthread_create failed for thread 6 of 8: Operation not permitted
dask-docker-notebook-1   | OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
dask-docker-notebook-1   | OpenBLAS blas_thread_init: pthread_create failed for thread 7 of 8: Operation not permitted
dask-docker-notebook-1   | OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
dask-docker-notebook-1   | Traceback (most recent call last):
dask-docker-notebook-1   |   File "/opt/conda/bin/jupyter-lab", line 10, in <module>
dask-docker-notebook-1   |     sys.exit(main())
dask-docker-notebook-1   |   File "/opt/conda/lib/python3.8/site-packages/jupyter_server/extension/application.py", line 584, in launch_instance
dask-docker-notebook-1   |     serverapp = cls.initialize_server(argv=args)
dask-docker-notebook-1   |   File "/opt/conda/lib/python3.8/site-packages/jupyter_server/extension/application.py", line 554, in initialize_server
dask-docker-notebook-1   |     serverapp.initialize(
dask-docker-notebook-1   |   File "/opt/conda/lib/python3.8/site-packages/traitlets/config/application.py", line 110, in inner
dask-docker-notebook-1   |     return method(app, *args, **kwargs)
dask-docker-notebook-1   |   File "/opt/conda/lib/python3.8/site-packages/jupyter_server/serverapp.py", line 2447, in initialize
dask-docker-notebook-1   |     self.init_server_extensions()
dask-docker-notebook-1   |   File "/opt/conda/lib/python3.8/site-packages/jupyter_server/serverapp.py", line 2211, in init_server_extensions
dask-docker-notebook-1   |     self.extension_manager.from_jpserver_extensions(self.jpserver_extensions)
dask-docker-notebook-1   |   File "/opt/conda/lib/python3.8/site-packages/jupyter_server/extension/manager.py", line 315, in from_jpserver_extensions
dask-docker-notebook-1   |     self.add_extension(name, enabled=enabled)
dask-docker-notebook-1   |   File "/opt/conda/lib/python3.8/site-packages/jupyter_server/extension/manager.py", line 322, in add_extension
dask-docker-notebook-1   |     extpkg = ExtensionPackage(name=extension_name, enabled=enabled)
dask-docker-notebook-1   |   File "/opt/conda/lib/python3.8/site-packages/jupyter_server/extension/manager.py", line 168, in __init__
dask-docker-notebook-1   |     super().__init__(*args, **kwargs)
dask-docker-notebook-1   |   File "/opt/conda/lib/python3.8/site-packages/traitlets/traitlets.py", line 1238, in __init__
dask-docker-notebook-1   |     super_kwargs[key] = value
dask-docker-notebook-1   |   File "/opt/conda/lib/python3.8/contextlib.py", line 120, in __exit__
dask-docker-notebook-1   |     next(self.gen)
dask-docker-notebook-1   |   File "/opt/conda/lib/python3.8/site-packages/traitlets/traitlets.py", line 1348, in hold_trait_notifications
dask-docker-notebook-1   |     value = trait._cross_validate(self, getattr(self, name))
dask-docker-notebook-1   |   File "/opt/conda/lib/python3.8/site-packages/traitlets/traitlets.py", line 729, in _cross_validate
dask-docker-notebook-1   |     value = obj._trait_validators[self.name](obj, proposal)
dask-docker-notebook-1   |   File "/opt/conda/lib/python3.8/site-packages/traitlets/traitlets.py", line 1132, in __call__
dask-docker-notebook-1   |     return self.func(*args, **kwargs)
dask-docker-notebook-1   |   File "/opt/conda/lib/python3.8/site-packages/jupyter_server/extension/manager.py", line 177, in _validate_name
dask-docker-notebook-1   |     self._module, self._metadata = get_metadata(name)
dask-docker-notebook-1   |   File "/opt/conda/lib/python3.8/site-packages/jupyter_server/extension/utils.py", line 55, in get_metadata
dask-docker-notebook-1   |     module = importlib.import_module(package_name)
dask-docker-notebook-1   |   File "/opt/conda/lib/python3.8/importlib/__init__.py", line 127, in import_module
dask-docker-notebook-1   |     return _bootstrap._gcd_import(name[level:], package, level)
dask-docker-notebook-1   |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
dask-docker-notebook-1   |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
dask-docker-notebook-1   |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
dask-docker-notebook-1   |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
dask-docker-notebook-1   |   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
dask-docker-notebook-1   |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
dask-docker-notebook-1   |   File "/opt/conda/lib/python3.8/site-packages/dask_labextension/__init__.py", line 6, in <module>
dask-docker-notebook-1   |     from .clusterhandler import DaskClusterHandler
dask-docker-notebook-1   |   File "/opt/conda/lib/python3.8/site-packages/dask_labextension/clusterhandler.py", line 11, in <module>
dask-docker-notebook-1   |     from .manager import manager
dask-docker-notebook-1   |   File "/opt/conda/lib/python3.8/site-packages/dask_labextension/manager.py", line 12, in <module>
dask-docker-notebook-1   |     from dask.distributed import Adaptive, utils
dask-docker-notebook-1   |   File "/opt/conda/lib/python3.8/site-packages/dask/distributed.py", line 11, in <module>
dask-docker-notebook-1   |     from distributed import *
dask-docker-notebook-1   |   File "/opt/conda/lib/python3.8/site-packages/distributed/__init__.py", line 4, in <module>
dask-docker-notebook-1   |     from distributed import config  # load distributed configuration first
dask-docker-notebook-1   |   File "/opt/conda/lib/python3.8/site-packages/distributed/config.py", line 14, in <module>
dask-docker-notebook-1   |     from distributed.compatibility import WINDOWS, logging_names
dask-docker-notebook-1   |   File "/opt/conda/lib/python3.8/site-packages/distributed/compatibility.py", line 44, in <module>
dask-docker-notebook-1   |     import numpy
dask-docker-notebook-1   |   File "/opt/conda/lib/python3.8/site-packages/numpy/__init__.py", line 140, in <module>
dask-docker-notebook-1   |     from . import core
dask-docker-notebook-1   |   File "/opt/conda/lib/python3.8/site-packages/numpy/core/__init__.py", line 23, in <module>
dask-docker-notebook-1   |     from . import multiarray
dask-docker-notebook-1   |   File "/opt/conda/lib/python3.8/site-packages/numpy/core/multiarray.py", line 10, in <module>
dask-docker-notebook-1   |     from . import overrides
dask-docker-notebook-1   |   File "/opt/conda/lib/python3.8/site-packages/numpy/core/overrides.py", line 6, in <module>
dask-docker-notebook-1   |     from numpy.core._multiarray_umath import (
dask-docker-notebook-1   | KeyboardInterrupt
dask-docker-notebook-1 exited with code 130

**Comment by jacobtomlinson** [comment]
Please share a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by xiongmozhou** [comment]
Official website an

docker network create dask

docker run --network dask -p 8787:8787 --name scheduler ghcr.io/dask/dask dask-scheduler  # start scheduler

docker run --network dask ghcr.io/dask/dask dask-worker scheduler:8786 # start worker
docker run --network dask ghcr.io/dask/dask dask-worker scheduler:8786 # start worker
docker run --network dask ghcr.io/dask/dask dask-worker scheduler:8786 # start worker

docker run --network dask -p 8888:8888 ghcr.io/dask/dask-notebook  # start Jupyter server


https://docs.dask.org/en/stable/deploying-docker.html

**Comment by furkankaradas** [comment]
Did you find any solution?

**Comment by jacobtomlinson** [comment]
There's been no activity here for a long time so I'm going to close this out. If you're still experiencing this issue please feel free to comment here and I can reopen it.
